# _*_ coding:utf-8 _*_

url_otc_huobi_buy_btc = "https://api-otc.huobi.pro/v1/otc/trade/list/public?coinId=1&tradeType=1&currentPage=1&payWay=&country="
url_otc_huobi_sell_btc ="https://api-otc.huobi.pro/v1/otc/trade/list/public?coinId=1&tradeType=0&currentPage=1&payWay=&country="
url_otc_huobi_buy_usdt = "https://api-otc.huobi.pro/v1/otc/trade/list/public?coinId=2&tradeType=1&currentPage=1&payWay=&country="
url_otc_huobi_sell_usdt = "https://api-otc.huobi.pro/v1/otc/trade/list/public?coinId=2&tradeType=0&currentPage=1&payWay=&country="
url_otc_coincola_buy_btc = "https://www.coincola.com/api/v1/advertisement/search?country_code=CN&currency=CNY&crypto_currency=BTC&sort_order=GENERAL&limit=10&offset=0&type=SELL&name=''"
url_otc_coincola_sell_btc = "https://www.coincola.com/api/v1/advertisement/search?country_code=CN&currency=CNY&crypto_currency=BTC&sort_order=GENERAL&limit=10&offset=0&type=BUY&name=''"
url_otc_coincola_buy_eth = "https://www.coincola.com/api/v1/advertisement/search?country_code=CN&currency=CNY&crypto_currency=ETH&sort_order=GENERAL&limit=10&offset=0&type=SELL&name=''"
url_otc_coincola_sell_eth = "https://www.coincola.com/api/v1/advertisement/search?country_code=CN&currency=CNY&crypto_currency=ETH&sort_order=GENERAL&limit=10&offset=0&type=BUY&name=''"
url_otc_coincola_buy_bch = "https://www.coincola.com/api/v1/advertisement/search?country_code=CN&currency=CNY&crypto_currency=BCH&sort_order=GENERAL&limit=10&offset=0&type=SELL&name=''"
url_otc_coincola_sell_bch = "https://www.coincola.com/api/v1/advertisement/search?country_code=CN&currency=CNY&crypto_currency=BCH&sort_order=GENERAL&limit=10&offset=0&type=BUY&name=''"
url_otc_okex_buy_btc = ""
url_otc_okex_sell_btc = ""
url_otc_okex_buy_eth = ""
url_otc_okex_sell_eth = ""